header:
    Accept: application/json
    Accept-Encoding: 'gzip, deflate, br'
    Accept-Language: 'zh-CN,zh;q=0.9'
    Cache-Control: no-cache
    Connection: keep-alive
    Content-Length: '44'
    content-type: application/x-www-form-urlencoded
    Host: ntx.qqtn.com
    Origin: 'http://127.0.0.1:19335'
    Pragma: no-cache
    Referer: 'https://servicewechat.com/wx581d41eca01df036/devtools/page-frame.html'
    sec-ch-ua: 'nwjs 74'
    Sec-Fetch-Dest: empty
    Sec-Fetch-Mode: cors
    Sec-Fetch-Site: cross-site
    Sec-Fetch-User: '?F'
    TK: 4b2f6bb5c01499a1b990ded72f2b46cb  #关键
    User-Agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 wechatdevtools/1.02.1907300 MicroMessenger/7.0.4 Language/zh_CN webview/'

ipproxy:

timedelay:

dbconfig:


