header:
    Accept: 'application/json'

    content-type: 'application/x-www-form-urlencoded'
    User-Agent: "Mozilla/5.0 (Linux; U; Android 2.3.6; zh-cn; GT-S5660 Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1 MicroMessenger/4.5.255"
    TK: '0eaf122095aa245fed0c09f15724913b'  #关键
    Proxy-Authorization: ''
timedelay:

dbconfig:

catchconfig:
    ipproxy:
        url: 'proxy.wandouip.com:8090'
        username: 'hy18022317541@163.com'
        pwd: 'hY18826079509'
    start: 1
    end: 100



